# Generated by Django 3.2.11 on 2022-01-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_auto_20220129_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
