# Generated by Django 3.2.11 on 2022-01-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_alter_video_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='type_video',
            field=models.CharField(choices=[('MOV', 'Movie'), ('TVS', 'TV Show'), ('SEA', 'Season'), ('PLY', 'Playlist')], default='PLY', max_length=3),
        ),
    ]
