# Generated by Django 3.2.11 on 2022-01-30 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_video_type_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='type_video',
        ),
    ]
