# Generated by Django 3.2.11 on 2022-01-30 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0009_alter_playlist_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('playlists.playlist',),
        ),
    ]
